#define DRUM_BASS_ACC   35
#define DRUM_BASS_1     36
#define SNARE_RIM       37
#define SNARE_ACC       38
#define CLAP            39
#define SNARE_ELEC      40
#define TOM_FLOOR_LOW   41
#define HIHAT_CLOSED    42
#define TOM_FLOOR_HIGH  43
#define HIHAT_PEDAL     44
#define TOM_LOW         45
#define HIHAT_OPEN      46
#define TOM_LOWMID      47
#define TOM_HIMID       48
#define CYM_CRASH_1     49
#define TOM_HI          50
#define CYM_RIDE_1      51
#define CYM_CHINESE     52
#define CYM_RIDE_BELL   53
#define TABOURINE       54
#define CYM_SPLASH      55
#define COWBELL         56
#define CYM_CRASH_2     57
#define VIBRASLAP       58
#define CYM_RIDE_2      59
#define BONGO_HI        60
#define BONGO_LOW       61
#define CONGA_HI_MUTE   62
#define CONGA_HI_OPEN   63
#define CONGA_LOW       64
#define TIMBALE_HI      65
#define TIMBALE_LOW     66   
#define AGOGO_HI        67
#define AGOGO_LOW       68
#define CABASA          69
#define MARACAS         70
#define WHISTLE_SHORT   71
#define WHISTLE_LONG    72
#define GUIRO_SHORT     73
#define GUIRO_LONG      74
#define CLAVES          75
#define WOODBLOCK_HI    76
#define WOODBLOCK_LOW   77
#define CUICA_MUTE      78
#define CUICA_OPEN      79
#define TRIANGLE_MUTE   80
#define TRIANGLE_OPEN   81